Exception on /tracking [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Administrator\Documents\My Programs\Python\Flask\Bus Tracking System API\resources\tracking.py", line 7, in get
    curso.execute(f'''SELECT * FROM Rawdata''')
NameError: name 'curso' is not defined
Exception on /buses [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 472, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 501, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
Exception on /buses [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 472, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 501, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
Exception on /tracking [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 472, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 501, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
Exception on /tracking [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 472, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\__init__.py", line 501, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\Flaskenv\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
